version: '3'

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - nginx-proxy-manager-data:/data
      - letsencrypt-certificates:/etc/letsencrypt
    networks:
      - mylab

networks:
  mylab:
    external: true

volumes:
  nginx-proxy-manager-data:
  letsencrypt-certificates: