version: '3'
networks:
  mylab:
    name: mylab
    external: true

services:
  traefik:
    image: traefik:2.9.1
    restart: always
    container_name: proxy_traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/traefik.yml:/etc/traefik/traefik.yml
      - ./configs/dynamic:/etc/traefik/dynamic
      - ./certificates/acme.json:/etc/traefik/acme/acme.json
    networks:
      - mylab
